# Generated by Django 6.0.4 on 2026-04-16 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='client_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.AddField(
            model_name='order',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='communicattion_channel',
            field=models.CharField(choices=[('tg', 'Telegram'), ('viber', 'Viber'), ('whatsapp', 'WhatsApp'), ('phone', 'Дзвiнок')], default='phone', max_length=20, verbose_name='Канал звязку'),
        ),
        migrations.AddField(
            model_name='order',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='applications/docs/', verbose_name='Документы'),
        ),
        migrations.AddField(
            model_name='order',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='applications/images/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(default='Kiev', max_length=100, verbose_name='Облость'),
        ),
    ]
