# Generated by Django 5.2.11 on 2026-04-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='communicattion_channel',
            new_name='communication_channel',
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
