# Generated by Django 6.0.4 on 2026-04-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_communicattion_channel_order_communication_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='хрыщатык 1', max_length=100, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Kiev', max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
