# Generated by Django 6.0.4 on 2026-04-23 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_order_latitude_order_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='author',
        ),
        migrations.RemoveField(
            model_name='order',
            name='communication_channel',
        ),
        migrations.RemoveField(
            model_name='order',
            name='document',
        ),
        migrations.RemoveField(
            model_name='order',
            name='photos',
        ),
        migrations.AddField(
            model_name='order',
            name='comm_channel',
            field=models.CharField(choices=[('phone', 'Дзвінок'), ('tg', 'Telegram'), ('viber', 'Viber'), ('whatsapp', 'WhatsApp')], default='phone', max_length=20, verbose_name="Канал зв'язку"),
        ),
        migrations.AddField(
            model_name='order',
            name='socials',
            field=models.TextField(blank=True, null=True, verbose_name='Соцмережі'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ПІБ Клієнта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Довгота'),
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Нова'), ('process', 'В роботі'), ('success', 'Виконана'), ('cancel', 'Скасована')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='OrderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/docs/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_documents', to='main.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='orders/photos/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_photos', to='main.order')),
            ],
        ),
    ]
