# Generated by Django 6.0.4 on 2026-04-25 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_order_options_remove_order_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='investor',
            field=models.ForeignKey(blank=True, limit_choices_to={'group_name': 'Investor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Призначеный инвестор'),
        ),
        migrations.AlterField(
            model_name='orderdocument',
            name='file',
            field=models.FileField(upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='orderphoto',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
