# Generated by Django 6.0.4 on 2026-04-25 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_order_investor_alter_orderdocument_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='investor',
            field=models.ForeignKey(blank=True, limit_choices_to={'group_name': 'Investors'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Призначеный инвестор'),
        ),
    ]
