# Generated by Django 6.0.4 on 2026-05-02 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_order_investor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='investor',
        ),
        migrations.AddField(
            model_name='order',
            name='investor',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Investors'}, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Призначеный инвестор'),
        ),
    ]
